CREATE TABLE inventories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT  NOT NULL,
    quantity   INTEGER NOT NULL,
    CONSTRAINT pk_inventories PRIMARY KEY (id)
);
